#!/bin/bash

set -e

echo "Flake8..."
flake8

echo "PyLint..."
pylint rich_traceroute tests

echo "MyPy..."
mypy --show-error-codes --ignore-missing-imports rich_traceroute tests

echo "Coverage & PyTest..."
coverage run \
    --source=rich_traceroute \
    -m pytest \
        -vsx
coverage report -m
