version: "3"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      # args:
      #   # Only used by the GitHub Actions workflow.
      #   INSTALL_FROM_GITHUB_SHA: ${GITHUB_SHA:-}
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      graphite:
        condition: service_healthy

  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: rich_traceroute
      MYSQL_USER: rich_traceroute_user
      MYSQL_PASSWORD: rich_traceroute_pass
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      interval: 2s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "true"]
    ports:
      - 15672:15672

  graphite:
    image: graphiteapp/graphite-statsd
    healthcheck:
      test: ["CMD", "true"]
    ports:
      - 8080:80
